SELECT OUTS.ANIMAL_ID , OUTS.ANIMAL_TYPE , OUTS.NAME 
FROM ANIMAL_OUTS AS OUTS LEFT OUTER JOIN ANIMAL_INS AS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE (INS.SEX_UPON_INTAKE = 'Intact Male'OR INS.SEX_UPON_INTAKE = 'Intact Female')AND
(OUTS.SEX_UPON_OUTCOME = 'Spayed Female' or
 OUTS.SEX_UPON_OUTCOME = 'Spayed Male' or
 OUTS.SEX_UPON_OUTCOME = 'Neutered Male' or 
 OUTS.SEX_UPON_OUTCOME = 'Neutered Female');
